// flow-typed signature: 37eb46b5ff7fa452ff966c098f158992
// flow-typed version: <<STUB>>/axios-es6_v^0.11.1/flow_v0.47.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'axios-es6'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'axios-es6' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'axios-es6/dist/axios' {
  declare module.exports: any;
}

declare module 'axios-es6/dist/axios.min' {
  declare module.exports: any;
}

declare module 'axios-es6/lib/adapters/http' {
  declare module.exports: any;
}

declare module 'axios-es6/lib/adapters/xhr' {
  declare module.exports: any;
}

declare module 'axios-es6/lib/axios' {
  declare module.exports: any;
}

declare module 'axios-es6/lib/core/InterceptorManager' {
  declare module.exports: any;
}

declare module 'axios-es6/lib/core/dispatchRequest' {
  declare module.exports: any;
}

declare module 'axios-es6/lib/defaults' {
  declare module.exports: any;
}

declare module 'axios-es6/lib/helpers/bind' {
  declare module.exports: any;
}

declare module 'axios-es6/lib/helpers/btoa' {
  declare module.exports: any;
}

declare module 'axios-es6/lib/helpers/buildURL' {
  declare module.exports: any;
}

declare module 'axios-es6/lib/helpers/combineURLs' {
  declare module.exports: any;
}

declare module 'axios-es6/lib/helpers/cookies' {
  declare module.exports: any;
}

declare module 'axios-es6/lib/helpers/deprecatedMethod' {
  declare module.exports: any;
}

declare module 'axios-es6/lib/helpers/isAbsoluteURL' {
  declare module.exports: any;
}

declare module 'axios-es6/lib/helpers/isURLSameOrigin' {
  declare module.exports: any;
}

declare module 'axios-es6/lib/helpers/parseHeaders' {
  declare module.exports: any;
}

declare module 'axios-es6/lib/helpers/settle' {
  declare module.exports: any;
}

declare module 'axios-es6/lib/helpers/spread' {
  declare module.exports: any;
}

declare module 'axios-es6/lib/helpers/transformData' {
  declare module.exports: any;
}

declare module 'axios-es6/lib/utils' {
  declare module.exports: any;
}

// Filename aliases
declare module 'axios-es6/dist/axios.js' {
  declare module.exports: $Exports<'axios-es6/dist/axios'>;
}
declare module 'axios-es6/dist/axios.min.js' {
  declare module.exports: $Exports<'axios-es6/dist/axios.min'>;
}
declare module 'axios-es6/index' {
  declare module.exports: $Exports<'axios-es6'>;
}
declare module 'axios-es6/index.js' {
  declare module.exports: $Exports<'axios-es6'>;
}
declare module 'axios-es6/lib/adapters/http.js' {
  declare module.exports: $Exports<'axios-es6/lib/adapters/http'>;
}
declare module 'axios-es6/lib/adapters/xhr.js' {
  declare module.exports: $Exports<'axios-es6/lib/adapters/xhr'>;
}
declare module 'axios-es6/lib/axios.js' {
  declare module.exports: $Exports<'axios-es6/lib/axios'>;
}
declare module 'axios-es6/lib/core/InterceptorManager.js' {
  declare module.exports: $Exports<'axios-es6/lib/core/InterceptorManager'>;
}
declare module 'axios-es6/lib/core/dispatchRequest.js' {
  declare module.exports: $Exports<'axios-es6/lib/core/dispatchRequest'>;
}
declare module 'axios-es6/lib/defaults.js' {
  declare module.exports: $Exports<'axios-es6/lib/defaults'>;
}
declare module 'axios-es6/lib/helpers/bind.js' {
  declare module.exports: $Exports<'axios-es6/lib/helpers/bind'>;
}
declare module 'axios-es6/lib/helpers/btoa.js' {
  declare module.exports: $Exports<'axios-es6/lib/helpers/btoa'>;
}
declare module 'axios-es6/lib/helpers/buildURL.js' {
  declare module.exports: $Exports<'axios-es6/lib/helpers/buildURL'>;
}
declare module 'axios-es6/lib/helpers/combineURLs.js' {
  declare module.exports: $Exports<'axios-es6/lib/helpers/combineURLs'>;
}
declare module 'axios-es6/lib/helpers/cookies.js' {
  declare module.exports: $Exports<'axios-es6/lib/helpers/cookies'>;
}
declare module 'axios-es6/lib/helpers/deprecatedMethod.js' {
  declare module.exports: $Exports<'axios-es6/lib/helpers/deprecatedMethod'>;
}
declare module 'axios-es6/lib/helpers/isAbsoluteURL.js' {
  declare module.exports: $Exports<'axios-es6/lib/helpers/isAbsoluteURL'>;
}
declare module 'axios-es6/lib/helpers/isURLSameOrigin.js' {
  declare module.exports: $Exports<'axios-es6/lib/helpers/isURLSameOrigin'>;
}
declare module 'axios-es6/lib/helpers/parseHeaders.js' {
  declare module.exports: $Exports<'axios-es6/lib/helpers/parseHeaders'>;
}
declare module 'axios-es6/lib/helpers/settle.js' {
  declare module.exports: $Exports<'axios-es6/lib/helpers/settle'>;
}
declare module 'axios-es6/lib/helpers/spread.js' {
  declare module.exports: $Exports<'axios-es6/lib/helpers/spread'>;
}
declare module 'axios-es6/lib/helpers/transformData.js' {
  declare module.exports: $Exports<'axios-es6/lib/helpers/transformData'>;
}
declare module 'axios-es6/lib/utils.js' {
  declare module.exports: $Exports<'axios-es6/lib/utils'>;
}
