// flow-typed signature: b1edf4fec06eeb41ec93dcdb3ac38ae9
// flow-typed version: <<STUB>>/firebase-bolt_v^0.8.2/flow_v0.47.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'firebase-bolt'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'firebase-bolt' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'firebase-bolt/dist/bolt' {
  declare module.exports: any;
}

declare module 'firebase-bolt/lib/ast' {
  declare module.exports: any;
}

declare module 'firebase-bolt/lib/bolt' {
  declare module.exports: any;
}

declare module 'firebase-bolt/lib/file-io' {
  declare module.exports: any;
}

declare module 'firebase-bolt/lib/firebase-rest' {
  declare module.exports: any;
}

declare module 'firebase-bolt/lib/logger' {
  declare module.exports: any;
}

declare module 'firebase-bolt/lib/parse-util' {
  declare module.exports: any;
}

declare module 'firebase-bolt/lib/rules-generator' {
  declare module.exports: any;
}

declare module 'firebase-bolt/lib/rules-parser' {
  declare module.exports: any;
}

declare module 'firebase-bolt/lib/simulator' {
  declare module.exports: any;
}

declare module 'firebase-bolt/lib/test/ast-test' {
  declare module.exports: any;
}

declare module 'firebase-bolt/lib/test/chat-test' {
  declare module.exports: any;
}

declare module 'firebase-bolt/lib/test/cli-test' {
  declare module.exports: any;
}

declare module 'firebase-bolt/lib/test/create-update-delete-test' {
  declare module.exports: any;
}

declare module 'firebase-bolt/lib/test/firebase-rest-test' {
  declare module.exports: any;
}

declare module 'firebase-bolt/lib/test/firebase-rules-test' {
  declare module.exports: any;
}

declare module 'firebase-bolt/lib/test/generator-test' {
  declare module.exports: any;
}

declare module 'firebase-bolt/lib/test/issue-118-test' {
  declare module.exports: any;
}

declare module 'firebase-bolt/lib/test/mail-test' {
  declare module.exports: any;
}

declare module 'firebase-bolt/lib/test/parser-test' {
  declare module.exports: any;
}

declare module 'firebase-bolt/lib/test/regexp-test' {
  declare module.exports: any;
}

declare module 'firebase-bolt/lib/test/sample-files' {
  declare module.exports: any;
}

declare module 'firebase-bolt/lib/test/test-helper' {
  declare module.exports: any;
}

declare module 'firebase-bolt/lib/test/util-test' {
  declare module.exports: any;
}

declare module 'firebase-bolt/lib/util' {
  declare module.exports: any;
}

// Filename aliases
declare module 'firebase-bolt/dist/bolt.js' {
  declare module.exports: $Exports<'firebase-bolt/dist/bolt'>;
}
declare module 'firebase-bolt/lib/ast.js' {
  declare module.exports: $Exports<'firebase-bolt/lib/ast'>;
}
declare module 'firebase-bolt/lib/bolt.js' {
  declare module.exports: $Exports<'firebase-bolt/lib/bolt'>;
}
declare module 'firebase-bolt/lib/file-io.js' {
  declare module.exports: $Exports<'firebase-bolt/lib/file-io'>;
}
declare module 'firebase-bolt/lib/firebase-rest.js' {
  declare module.exports: $Exports<'firebase-bolt/lib/firebase-rest'>;
}
declare module 'firebase-bolt/lib/logger.js' {
  declare module.exports: $Exports<'firebase-bolt/lib/logger'>;
}
declare module 'firebase-bolt/lib/parse-util.js' {
  declare module.exports: $Exports<'firebase-bolt/lib/parse-util'>;
}
declare module 'firebase-bolt/lib/rules-generator.js' {
  declare module.exports: $Exports<'firebase-bolt/lib/rules-generator'>;
}
declare module 'firebase-bolt/lib/rules-parser.js' {
  declare module.exports: $Exports<'firebase-bolt/lib/rules-parser'>;
}
declare module 'firebase-bolt/lib/simulator.js' {
  declare module.exports: $Exports<'firebase-bolt/lib/simulator'>;
}
declare module 'firebase-bolt/lib/test/ast-test.js' {
  declare module.exports: $Exports<'firebase-bolt/lib/test/ast-test'>;
}
declare module 'firebase-bolt/lib/test/chat-test.js' {
  declare module.exports: $Exports<'firebase-bolt/lib/test/chat-test'>;
}
declare module 'firebase-bolt/lib/test/cli-test.js' {
  declare module.exports: $Exports<'firebase-bolt/lib/test/cli-test'>;
}
declare module 'firebase-bolt/lib/test/create-update-delete-test.js' {
  declare module.exports: $Exports<'firebase-bolt/lib/test/create-update-delete-test'>;
}
declare module 'firebase-bolt/lib/test/firebase-rest-test.js' {
  declare module.exports: $Exports<'firebase-bolt/lib/test/firebase-rest-test'>;
}
declare module 'firebase-bolt/lib/test/firebase-rules-test.js' {
  declare module.exports: $Exports<'firebase-bolt/lib/test/firebase-rules-test'>;
}
declare module 'firebase-bolt/lib/test/generator-test.js' {
  declare module.exports: $Exports<'firebase-bolt/lib/test/generator-test'>;
}
declare module 'firebase-bolt/lib/test/issue-118-test.js' {
  declare module.exports: $Exports<'firebase-bolt/lib/test/issue-118-test'>;
}
declare module 'firebase-bolt/lib/test/mail-test.js' {
  declare module.exports: $Exports<'firebase-bolt/lib/test/mail-test'>;
}
declare module 'firebase-bolt/lib/test/parser-test.js' {
  declare module.exports: $Exports<'firebase-bolt/lib/test/parser-test'>;
}
declare module 'firebase-bolt/lib/test/regexp-test.js' {
  declare module.exports: $Exports<'firebase-bolt/lib/test/regexp-test'>;
}
declare module 'firebase-bolt/lib/test/sample-files.js' {
  declare module.exports: $Exports<'firebase-bolt/lib/test/sample-files'>;
}
declare module 'firebase-bolt/lib/test/test-helper.js' {
  declare module.exports: $Exports<'firebase-bolt/lib/test/test-helper'>;
}
declare module 'firebase-bolt/lib/test/util-test.js' {
  declare module.exports: $Exports<'firebase-bolt/lib/test/util-test'>;
}
declare module 'firebase-bolt/lib/util.js' {
  declare module.exports: $Exports<'firebase-bolt/lib/util'>;
}
