// flow-typed signature: 642ff940b0e20c6db6cdf6c35a6416ad
// flow-typed version: <<STUB>>/uid-safe_v^2.1.4/flow_v0.47.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'uid-safe'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'uid-safe' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */


// Filename aliases
declare module 'uid-safe/index' {
  declare module.exports: $Exports<'uid-safe'>;
}
declare module 'uid-safe/index.js' {
  declare module.exports: $Exports<'uid-safe'>;
}
