export const ADD_CART_ITEM = 'ADD_CART_ITEM';
export const ADD_CART_ITEM_FAILED = 'ADD_CART_ITEM_FAILED';
export const REMOVE_CART_ITEM = 'REMOVE_CART_ITEM';
export const REMOVE_CART_ITEM_FAILED = 'REMOVE_CART_ITEM_FAILED';
export const GET_INITIAL_STATE = 'GET_INITIAL_STATE';
export const HIDRATE_INITIAL_STATE = 'HIDRATE_INITIAL_STATE';

// item details
export const GET_ITEM = 'GET_ITEM';
export const GET_ITEM_FAILED = 'GET_ITEM_FAILED';

// contact form
export const SEND_CONTACT_MSG_FAILED = 'SEND_CONTACT_MSG_FAILED';
export const SEND_CONTACT_MSG = 'SEND_CONTACT_MSG';
